version: '3.9'

services:
  livekit:
    container_name: livekit
    build: .
    ports:
      - "85:8000"
    restart: always
    networks:
      - livekit-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: livekit-ngrok
    restart: always
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=302D9LscAMvGkNMmjjUdgedbt7w_6Hstkmff17iTqQ5SAxLX1
    command: http livekit:8000
    networks:
      - livekit-net

networks:
  livekit-net:
